version: '2'
services:
  test_db:
    image: postgres:9.5
    expose:
      - 5433
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: everest
      POSTGRES_PASSWORD: everest
      POSTGRES_DB: test_everest