version: '2'
services:
  db_rocket:
    image: postgres:9.5
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: rocket
      POSTGRES_USER: rocket
      POSTGRES_DB: rocket