version: '2'
services:
  kibana:
    image: kibana:4.5
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    ports:
      - "5601:5601"
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
      - logstash
    expose:
      - 5601

  elasticsearch:
    image: jesuejunior/elasticsearch
    volumes:
       - /elk/elasticsearch/data:/opt/elasticsearch/data:Z
       - /elk/elasticsearch/logs:/opt/elasticsearch/logs:Z
    ports:
      - "9200:9200"
      - "9300:9300"
    expose:
      - 9200
      - 9300

  logstash:
    image: jesuejunior/logstash
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    volumes:
      - /elk/logstash:/etc/logstash:Z
    ports:
      - "28777:28777"
      - "28778:28778"
      - "28779:28779"
    expose:
      - 28777
      - 28778
      - 28779
