version: '2'
services:
  kibana:
    image: kibana:4.5
#    volumes:
#      - /elk/kibana:/opt/kibana:rw
    environment:
      - "ELASTICSEARCH_URL=http://192.168.1.24:9200"
    ports:
      - "5601:5601"
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
      - logstash
    expose:
      - 5601

  elasticsearch:
    image: jesuejunior/elasticsearch
#    volumes:
#       - /elk/elasticsearch/data:/opt/elasticsearch/data:rw
#      - /elk/elasticsearch/logs:/opt/elasticsearch/logs:rw
    ports:
      - "9200:9200"
      - "9300:9300"
    expose:
      - 9200
      - 9300

  logstash:
    image: jesuejunior/logstash
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    volumes:
      - /elk/logstash:/etc/logstash:rw
    ports:
      - "28777:28777"
    expose:
      - 28777
