version: '2'
services:
  registry:
    image: registry:2.4
    env_file:
      - registry.env
    volumes:
      - /opt/registry/tmp:/tmp/registry-dev:Z
      - /opt/registry/lib:/var/lib/registry:Z
      - /opt/nginx/certs:/certs:Z
    expose:
      - 5000
    networks:
      apps_network:
        ipv4_address: 172.16.2.11
  nginx:
      image: jesuejunior/nginx:apps
      networks:
        apps_network:
          ipv4_address: 172.16.2.10
      env_file:
        - registry.env
      volumes:
        - /opt/nginx/files:/app/files:Z
        - /opt/nginx/certs:/opt/nginx/certs:Z
      ports:
        - "80:80"
        - "443:443"
      expose:
        - 80
        - 443
      links:
        - registry:app

networks:
  apps_network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.2.0/24
        ip_range: 172.16.2.0/24
        gateway: 172.16.2.1
