version: '2'
services:
    sentry:
        image: sentry:8.2
        env_file:
            - sentry.env
        volumes:
            - /var/lib/sentry/files:/var/lib/sentry/files:rw
        links:
            - redis:redis
            - postgres:postgres
            - worker:worker
            - beat:beat
        depends_on:
            - postgres
            - redis
        ports:
            - "9000:9000"
        expose:
            - 9000

    worker:
        image: sentry:8.2
        env_file:
            - sentry.env
        volumes:
            - /var/lib/sentry/files:/var/lib/sentry/files:rw
        links:
            - redis:redis
            - postgres:postgres
        depends_on:
            - postgres
            - redis
        command: celery worker

    beat:
        image: sentry:8.2
        env_file:
            - sentry.env
        volumes:
            - /var/lib/sentry/files:/var/lib/sentry/files:rw
        links:
            - redis:redis
            - postgres:postgres
        depends_on:
            - postgres
            - redis
        command: celery beat

    redis:
        image: redis:3.0.7-alpine
        #ports:
        #    - "6379:6379"

    postgres:
        image: postgres:9
        env_file:
            - sentry.env
        #ports:
        #    - "5432:5432"
        volumes:
            - /var/lib/sentry/postgresql/data:/var/lib/postgresql/data:rw

