version: '2'
services:
    sentry:
        image: sentry:8.4
        env_file:
            - sentry.env
        volumes:
            - /opt/sentry/files:/var/lib/sentry/files:Z
        links:
            - redis:redis
            - postgres:postgres
            - worker:worker
            - beat:beat
        depends_on:
            - postgres
            - redis
        ports:
            - "9000:9000"
        expose:
            - 9000
    worker:
        image: sentry:8.4
        env_file:
            - sentry.env
        volumes:
            - /opt/sentry/files:/var/lib/sentry/files:Z
        links:
            - redis:redis
            - postgres:postgres
        depends_on:
            - postgres
            - redis
        command: celery worker
    beat:
        image: sentry:8.4
        env_file:
            - sentry.env
        volumes:
            - /opt/sentry/files:/var/lib/sentry/files:Z
        links:
            - redis:redis
            - postgres:postgres
        depends_on:
            - postgres
            - redis
        command: celery beat
    redis:
        image: redis:3.0.7-alpine
        #ports:
        #    - "6379:6379"
    postgres:
        image: postgres:9.5.2
        env_file:
            - sentry.env
        ports:
            - "5432:5432"
        volumes:
            - /opt/sentry/postgresql/data:/var/lib/postgresql/data:Z

