---
- hosts: elk
  vars:
    project: elk
    app_name: elk

  tasks:
    - include: ../docker.compose.yml
    #FIX-ME: It's a bad smell, it'll need more time to investigate on centos permissions
    - name: Set permission for group in /opt/elk
      become: yes
      file:
        path: /opt/elk
        state: directory
        recurse: yes
        mode: 0777
        owner: rocket
        group: users
