---
- hosts: registry
  vars:
    project: registry
    app_name: registry

  tasks:
    - name: creating certs folder in /opt
      become: yes
      file:
        path: /opt/nginx/certs
        state: directory
        recurse: yes
        mode: 0777
        owner: rocket
        group: docker
    - name: Coping nginx certs files (domain.crt)
      become: yes
      copy:
        src: ../../files/certs/domain.crt
        dest: /opt/nginx/certs/domain.crt
        owner: rocket
        group: docker
        mode: 0755
    - name: Coping nginx certs files (domain.key)
      become: yes
      copy:
        src: ../../files/certs/domain.key
        dest: /opt/nginx/certs/domain.key
        owner: rocket
        group: docker
        mode: 0755
    - name: creating certs folder to docker
      become: yes
      file:
        path: /etc/docker/certs.d/docker.rj1.muxi.corp
        state: directory
        recurse: yes
        mode: 0777
        owner: rocket
        group: docker
    - name: Coping registry certs files (domain.crt)
      become: yes
      copy:
        src: ../../files/certs/domain.crt
        dest: /etc/docker/certs.d/docker.rj1.muxi.corp/ca.crt
        owner: rocket
        group: docker
        mode: 0755

    - include: ../docker.compose.yml
