---
- hosts: all
  pre_tasks:
    - name: Update all packages if needed. [testing]
      become: yes
      yum: name=* state=latest update_cache=yes
  vars_files:
    - ../vars/main.yml
  vars:
    - has_private_registry: true
  roles:
  - docker

  tasks:
    - name: Installing base libs
      become: yes
      yum:
        name: "{{ item }}"
        state: installed
      with_items:
        - zsh
        - python-devel
        - python-pip
        - python-pycurl
        - vim
        - htop

    - name: (pip) Installing docker-compose
      become: yes
      pip:
        name: "{{ item }}"
#        version: 1.7.1
        state: latest
      with_items:
        - docker-compose
        - backports.ssl-match-hostname

    - name: Install NTP
      become: yes
      yum: name=ntp state=installed

    - name: Colocando NTP para executar
      become: yes
      service: name=ntpd state=started enabled=yes

    - name: Creating rocket user
      become: yes
      user:
        name: rocket
        groups: wheel,adm,docker
        state: present
        shell: /bin/zsh
        password: $6$rounds=656000$W0Mlifk9FN2zui8O$YPYDz13b1VorlyjaBdvMpN1dp.YrcoJOzFgugHbiVrh9X4dvubV70O3LM.yOS6hmmVJziXJUBuxft72RO9ftD1

    - name: Create tools directory
      become: yes
      file:
        path: /home/rocket/tools
        state: directory
        mode: 0755
        owner: rocket
        group: docker

    - name: Copy comlurb.py
      become: yes
      copy:
        src: ../files/comlurb.py
        dest: /home/rocket/tools/comlurb.py
        owner: rocket
        group: docker
        mode: 0755

    - name: Coping registry certs files (ca.crt) -> {{ ansible_hostname }}
      become: yes
      copy:
        src: ../../files/certs/domain.crt
        dest: /etc/pki/ca-trust/source/anchors/ca.crt
        mode: 0755
      when: has_private_registry

    - name: Updating trusted CA
      become: yes
      command: update-ca-trust
      when: has_private_registry

    #FIX-ME: disabled temporarily
#    - name: Login to registry Docker Hub
#      command: docker login --email="{{ registry_mail }}" --password="{{ registry_pass }}" --username="{{ registry_user }}"

