- name: Create {{ app_name }} directory
  become: yes
  file:
    path: /home/rocket/tools/{{ app_name }}
    state: directory
    mode: 0755
    owner: rocket
    group: docker

- name: Copy compose file for {{ app_name }}
  become: yes
  copy:
    src: ../../files/core/{{ app_name }}.deploy.yml
    dest: /home/rocket/tools/{{ app_name }}/docker-compose.yml
    owner: rocket
    group: docker
    mode: 0755

- name: Copy {{ app_name }} variable file
  become: yes
  copy:
    src: ../../files/core/{{ app_name }}.env
    dest: /home/rocket/tools/{{ app_name }}/{{ app_name }}.env
    owner: rocket
    group: docker
    mode: 0755

- name: Running docker compose PULL for check the new image
  become: yes
  command: docker-compose pull  chdir=/home/rocket/tools/{{ app_name }}

- name: Running docker compose UP
  become: yes
  command: docker-compose  --project-name="{{ project }}" up -d  chdir=/home/rocket/tools/{{ app_name }}


#- name: Executing comlurb.py
#  become: yes
#  command: python comlurb.py {{ app_name }}/docker-compose.yml chdir=/home/rocket/tools
