
- name: (yum) Install epel-release repository
  become: yes
  yum: name=epel-release state=present
  
- name: be sure libselinux-python are installed  
  become: yes
  yum: name=libselinux-python state=present

- name: Install Docker Repository
  become: yes
  template: src=docker-repo.j2 dest=/etc/yum.repos.d/docker.repo

- name: (yum) Install SELinux python bindings
  become: yes
  yum: name=libselinux-python state=present
  when: ansible_selinux is defined and ansible_pkg_mgr == 'yum'
 
- name: (yum) Install Docker Engine
  become: yes
  yum: name={{ docker_yum_package }} state=present
  when: ansible_pkg_mgr == 'yum'

- name: (dnf) Install SELinux python bindings
  become: yes
  dnf: name=libselinux-python state=present
  when: ansible_selinux is defined and ansible_pkg_mgr == 'dnf'
  
- name: (dnf) Install Docker Engine
  become: yes
  dnf: name=docker-engine state=present
  when: ansible_pkg_mgr == 'dnf'

